# Generated by Django 5.2.1 on 2025-10-27 10:14

import django.db.models.deletion
from django.db import migrations, models

import maintenance.models
import pgtrigger.compiler
import pgtrigger.migrations

import apps.common.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [("pghistory", "0007_auto_20250421_0444")]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                (
                    "audios_slow_down_enable",
                    models.BooleanField(
                        default=False, verbose_name="Habilitar disminuir velocidad de audios"
                    ),
                ),
                (
                    "audios_slow_down_factor",
                    models.FloatField(
                        default=0.95,
                        help_text="Mínimo 0.7, máximo 0.95",
                        verbose_name="Factor disminuir velocidad de audios",
                    ),
                ),
                (
                    "process_list_refresh",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="Refresco Lista de Procesos"
                    ),
                ),
                (
                    "transcribe_get_results_max_tries",
                    models.PositiveSmallIntegerField(
                        default=200, verbose_name="AWS máximo de intentos"
                    ),
                ),
                (
                    "transcribe_get_results_seconds_between",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="AWS segundos entre intentos"
                    ),
                ),
                (
                    "localai_mode",
                    models.PositiveSmallIntegerField(
                        choices=apps.common.utils.get_localai_modes,
                        default=1,
                        help_text="<ul><li>Calidad -> mejores transcripciones.</li><li>Performance -> incrementa la velocidad de transcripción, sacrificando ligeramente la calidad</li></ul>",
                        verbose_name="IA Local modo",
                    ),
                ),
                (
                    "localai_use_cpu",
                    models.BooleanField(
                        default=False,
                        help_text="<ul><li>Solo en casos de elevada carga, asignar tareas de transcripción a la CPU.</li><li>Utilizará el mismo modo que las GPU</li></ul>",
                        verbose_name="IA Local usar CPU",
                    ),
                ),
                (
                    "localai_get_max_tries",
                    models.PositiveSmallIntegerField(
                        default=1000, verbose_name="IA Local máximo intentos"
                    ),
                ),
                (
                    "localai_get_seconds_between",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="IA Local segundos entre intentos"
                    ),
                ),
                (
                    "localai_track_stats",
                    models.BooleanField(default=True, verbose_name="Recolectar estadísticas"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comentarios")),
            ],
            options={
                "verbose_name": "Configuración General",
                "verbose_name_plural": "Configuraciones Generales",
            },
            bases=(models.Model, maintenance.models.MaintenanceMixin),
        ),
        migrations.CreateModel(
            name="ConfigEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                (
                    "audios_slow_down_enable",
                    models.BooleanField(
                        default=False, verbose_name="Habilitar disminuir velocidad de audios"
                    ),
                ),
                (
                    "audios_slow_down_factor",
                    models.FloatField(
                        default=0.95,
                        help_text="Mínimo 0.7, máximo 0.95",
                        verbose_name="Factor disminuir velocidad de audios",
                    ),
                ),
                (
                    "process_list_refresh",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="Refresco Lista de Procesos"
                    ),
                ),
                (
                    "transcribe_get_results_max_tries",
                    models.PositiveSmallIntegerField(
                        default=200, verbose_name="AWS máximo de intentos"
                    ),
                ),
                (
                    "transcribe_get_results_seconds_between",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="AWS segundos entre intentos"
                    ),
                ),
                (
                    "localai_mode",
                    models.PositiveSmallIntegerField(
                        choices=apps.common.utils.get_localai_modes,
                        default=1,
                        help_text="<ul><li>Calidad -> mejores transcripciones.</li><li>Performance -> incrementa la velocidad de transcripción, sacrificando ligeramente la calidad</li></ul>",
                        verbose_name="IA Local modo",
                    ),
                ),
                (
                    "localai_use_cpu",
                    models.BooleanField(
                        default=False,
                        help_text="<ul><li>Solo en casos de elevada carga, asignar tareas de transcripción a la CPU.</li><li>Utilizará el mismo modo que las GPU</li></ul>",
                        verbose_name="IA Local usar CPU",
                    ),
                ),
                (
                    "localai_get_max_tries",
                    models.PositiveSmallIntegerField(
                        default=1000, verbose_name="IA Local máximo intentos"
                    ),
                ),
                (
                    "localai_get_seconds_between",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="IA Local segundos entre intentos"
                    ),
                ),
                (
                    "localai_track_stats",
                    models.BooleanField(default=True, verbose_name="Recolectar estadísticas"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comentarios")),
            ],
            options={"abstract": False},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="config",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "common_configevent" ("audios_slow_down_enable", "audios_slow_down_factor", "comment", "create_date", "id", "localai_get_max_tries", "localai_get_seconds_between", "localai_mode", "localai_track_stats", "localai_use_cpu", "modify_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "process_list_refresh", "transcribe_get_results_max_tries", "transcribe_get_results_seconds_between") VALUES (NEW."audios_slow_down_enable", NEW."audios_slow_down_factor", NEW."comment", NEW."create_date", NEW."id", NEW."localai_get_max_tries", NEW."localai_get_seconds_between", NEW."localai_mode", NEW."localai_track_stats", NEW."localai_use_cpu", NEW."modify_date", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."process_list_refresh", NEW."transcribe_get_results_max_tries", NEW."transcribe_get_results_seconds_between"); RETURN NULL;',
                    hash="107bc7f38e66c98396c610f430a75ee87e9eacaa",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_da2bc",
                    table="common_config",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="config",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "common_configevent" ("audios_slow_down_enable", "audios_slow_down_factor", "comment", "create_date", "id", "localai_get_max_tries", "localai_get_seconds_between", "localai_mode", "localai_track_stats", "localai_use_cpu", "modify_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "process_list_refresh", "transcribe_get_results_max_tries", "transcribe_get_results_seconds_between") VALUES (NEW."audios_slow_down_enable", NEW."audios_slow_down_factor", NEW."comment", NEW."create_date", NEW."id", NEW."localai_get_max_tries", NEW."localai_get_seconds_between", NEW."localai_mode", NEW."localai_track_stats", NEW."localai_use_cpu", NEW."modify_date", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."process_list_refresh", NEW."transcribe_get_results_max_tries", NEW."transcribe_get_results_seconds_between"); RETURN NULL;',
                    hash="041cfde1071cae2c65e87ada43031dc0f539062d",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_bb5d8",
                    table="common_config",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="configevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="configevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="common.config",
            ),
        ),
    ]
