# Generated by Django 5.2.1 on 2025-10-14 17:06

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import maintenance.models
import maintenance.validators
import pgtrigger.compiler
import pgtrigger.migrations

import apps.analytics.utils
import apps.users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("pghistory", "0007_auto_20250421_0444")]

    operations = [
        migrations.CreateModel(
            name="CampaignEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Nombre")),
                (
                    "is_active",
                    models.BooleanField(default=True, editable=False, verbose_name="Activo"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Nombre")),
                (
                    "is_active",
                    models.BooleanField(default=True, editable=False, verbose_name="Activo"),
                ),
                (
                    "can_export_processresult",
                    models.BooleanField(default=False, verbose_name="Puede exportar resultados"),
                ),
                (
                    "can_history_processresult",
                    models.BooleanField(
                        default=False, verbose_name="Puede ver histórico de cambios"
                    ),
                ),
                (
                    "scope_processresult",
                    models.SmallIntegerField(
                        choices=apps.analytics.utils.get_scopes,
                        default=0,
                        verbose_name="Alcance del permiso",
                    ),
                ),
                (
                    "can_add_process",
                    models.BooleanField(default=False, verbose_name="Puede añadir procesos"),
                ),
                (
                    "can_edit_process",
                    models.BooleanField(default=False, verbose_name="Puede editar procesos"),
                ),
                (
                    "can_delete_process",
                    models.BooleanField(
                        default=False, verbose_name="Puede eliminar/reactivar procesos"
                    ),
                ),
                (
                    "can_history_process",
                    models.BooleanField(
                        default=False, verbose_name="Puede ver histórico de cambios"
                    ),
                ),
                (
                    "scope_process",
                    models.SmallIntegerField(
                        choices=apps.analytics.utils.get_scopes,
                        default=0,
                        verbose_name="Alcance del permiso",
                    ),
                ),
                (
                    "can_add_typification",
                    models.BooleanField(default=False, verbose_name="Puede añadir tipificaciones"),
                ),
                (
                    "can_edit_typification",
                    models.BooleanField(default=False, verbose_name="Puede editar tipificaciones"),
                ),
                (
                    "can_delete_typification",
                    models.BooleanField(
                        default=False, verbose_name="Puede eliminar/reactivar tipificaciones"
                    ),
                ),
                (
                    "can_import_typification",
                    models.BooleanField(
                        default=False, verbose_name="Puede importar tipificaciones"
                    ),
                ),
                (
                    "can_export_typification",
                    models.BooleanField(
                        default=False, verbose_name="Puede exportar tipificaciones"
                    ),
                ),
                (
                    "can_history_typification",
                    models.BooleanField(
                        default=False, verbose_name="Puede ver histórico de cambios"
                    ),
                ),
                (
                    "scope_typification",
                    models.SmallIntegerField(
                        choices=apps.analytics.utils.get_scopes,
                        default=0,
                        verbose_name="Alcance del permiso",
                    ),
                ),
                (
                    "can_add_wordlist",
                    models.BooleanField(
                        default=False, verbose_name="Puede añadir palabras personalizadas"
                    ),
                ),
                (
                    "can_edit_wordlist",
                    models.BooleanField(
                        default=False, verbose_name="Puede editar palabras personalizadas"
                    ),
                ),
                (
                    "can_delete_wordlist",
                    models.BooleanField(
                        default=False,
                        verbose_name="Puede eliminar/reactivar palabras personalizadas",
                    ),
                ),
                (
                    "can_import_wordlist",
                    models.BooleanField(
                        default=False, verbose_name="Puede importar palabras personalizadas"
                    ),
                ),
                (
                    "can_export_wordlist",
                    models.BooleanField(
                        default=False, verbose_name="Puede exportar palabras personalizadas"
                    ),
                ),
                (
                    "can_history_wordlist",
                    models.BooleanField(
                        default=False, verbose_name="Puede ver histórico de cambios"
                    ),
                ),
                (
                    "scope_wordlist",
                    models.SmallIntegerField(
                        choices=apps.analytics.utils.get_scopes,
                        default=0,
                        verbose_name="Alcance del permiso",
                    ),
                ),
                (
                    "can_add_agent",
                    models.BooleanField(default=False, verbose_name="Puede añadir asesores"),
                ),
                (
                    "can_edit_agent",
                    models.BooleanField(default=False, verbose_name="Puede editar asesores"),
                ),
                (
                    "can_delete_agent",
                    models.BooleanField(
                        default=False, verbose_name="Puede eliminar/reactivar asesores"
                    ),
                ),
                (
                    "can_import_agent",
                    models.BooleanField(default=False, verbose_name="Puede importar asesores"),
                ),
                (
                    "can_export_agent",
                    models.BooleanField(default=False, verbose_name="Puede exportar asesores"),
                ),
                (
                    "can_history_agent",
                    models.BooleanField(
                        default=False, verbose_name="Puede ver histórico de cambios"
                    ),
                ),
                (
                    "scope_agent",
                    models.SmallIntegerField(
                        choices=apps.analytics.utils.get_scopes,
                        default=0,
                        verbose_name="Alcance del permiso",
                    ),
                ),
                (
                    "can_add_campaign",
                    models.BooleanField(default=False, verbose_name="Puede añadir campañas"),
                ),
                (
                    "can_edit_campaign",
                    models.BooleanField(default=False, verbose_name="Puede editar campañas"),
                ),
                (
                    "can_delete_campaign",
                    models.BooleanField(
                        default=False, verbose_name="Puede eliminar/reactivar campañas"
                    ),
                ),
                (
                    "can_export_campaign",
                    models.BooleanField(default=False, verbose_name="Puede exportar campañas"),
                ),
                (
                    "can_history_campaign",
                    models.BooleanField(
                        default=False, verbose_name="Puede ver histórico de cambios"
                    ),
                ),
                (
                    "can_edit_config",
                    models.BooleanField(default=False, verbose_name="Puede editar configuraciones"),
                ),
                (
                    "can_history_config",
                    models.BooleanField(
                        default=False, verbose_name="Puede ver histórico de cambios"
                    ),
                ),
                (
                    "can_add_user",
                    models.BooleanField(default=False, verbose_name="Puede añadir usuarios"),
                ),
                (
                    "can_edit_user",
                    models.BooleanField(default=False, verbose_name="Puede editar usuarios"),
                ),
                (
                    "can_delete_user",
                    models.BooleanField(
                        default=False, verbose_name="Puede eliminar/reactivar usuarios"
                    ),
                ),
                (
                    "can_import_user",
                    models.BooleanField(default=False, verbose_name="Puede importar usuarios"),
                ),
                (
                    "can_export_user",
                    models.BooleanField(default=False, verbose_name="Puede exportar usuarios"),
                ),
                (
                    "can_history_user",
                    models.BooleanField(
                        default=False, verbose_name="Puede ver histórico de cambios"
                    ),
                ),
                (
                    "can_change_user_password",
                    models.BooleanField(default=False, verbose_name="Puede cambiar la contraseña"),
                ),
                (
                    "scope_user",
                    models.SmallIntegerField(
                        choices=apps.analytics.utils.get_scopes,
                        default=0,
                        verbose_name="Alcance del permiso",
                    ),
                ),
                (
                    "can_add_role",
                    models.BooleanField(default=False, verbose_name="Puede añadir roles"),
                ),
                (
                    "can_edit_role",
                    models.BooleanField(default=False, verbose_name="Puede editar roles"),
                ),
                (
                    "can_delete_role",
                    models.BooleanField(
                        default=False, verbose_name="Puede eliminar/reactivar roles"
                    ),
                ),
                (
                    "can_export_role",
                    models.BooleanField(default=False, verbose_name="Puede exportar roles"),
                ),
                (
                    "can_history_role",
                    models.BooleanField(
                        default=False, verbose_name="Puede ver histórico de cambios"
                    ),
                ),
            ],
            options={"verbose_name": "Rol", "verbose_name_plural": "Roles", "ordering": ("name",)},
            bases=(models.Model, maintenance.models.MaintenanceMixin),
        ),
        migrations.CreateModel(
            name="RoleEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Nombre")),
                (
                    "is_active",
                    models.BooleanField(default=True, editable=False, verbose_name="Activo"),
                ),
                (
                    "can_export_processresult",
                    models.BooleanField(default=False, verbose_name="Puede exportar resultados"),
                ),
                (
                    "can_history_processresult",
                    models.BooleanField(
                        default=False, verbose_name="Puede ver histórico de cambios"
                    ),
                ),
                (
                    "scope_processresult",
                    models.SmallIntegerField(
                        choices=apps.analytics.utils.get_scopes,
                        default=0,
                        verbose_name="Alcance del permiso",
                    ),
                ),
                (
                    "can_add_process",
                    models.BooleanField(default=False, verbose_name="Puede añadir procesos"),
                ),
                (
                    "can_edit_process",
                    models.BooleanField(default=False, verbose_name="Puede editar procesos"),
                ),
                (
                    "can_delete_process",
                    models.BooleanField(
                        default=False, verbose_name="Puede eliminar/reactivar procesos"
                    ),
                ),
                (
                    "can_history_process",
                    models.BooleanField(
                        default=False, verbose_name="Puede ver histórico de cambios"
                    ),
                ),
                (
                    "scope_process",
                    models.SmallIntegerField(
                        choices=apps.analytics.utils.get_scopes,
                        default=0,
                        verbose_name="Alcance del permiso",
                    ),
                ),
                (
                    "can_add_typification",
                    models.BooleanField(default=False, verbose_name="Puede añadir tipificaciones"),
                ),
                (
                    "can_edit_typification",
                    models.BooleanField(default=False, verbose_name="Puede editar tipificaciones"),
                ),
                (
                    "can_delete_typification",
                    models.BooleanField(
                        default=False, verbose_name="Puede eliminar/reactivar tipificaciones"
                    ),
                ),
                (
                    "can_import_typification",
                    models.BooleanField(
                        default=False, verbose_name="Puede importar tipificaciones"
                    ),
                ),
                (
                    "can_export_typification",
                    models.BooleanField(
                        default=False, verbose_name="Puede exportar tipificaciones"
                    ),
                ),
                (
                    "can_history_typification",
                    models.BooleanField(
                        default=False, verbose_name="Puede ver histórico de cambios"
                    ),
                ),
                (
                    "scope_typification",
                    models.SmallIntegerField(
                        choices=apps.analytics.utils.get_scopes,
                        default=0,
                        verbose_name="Alcance del permiso",
                    ),
                ),
                (
                    "can_add_wordlist",
                    models.BooleanField(
                        default=False, verbose_name="Puede añadir palabras personalizadas"
                    ),
                ),
                (
                    "can_edit_wordlist",
                    models.BooleanField(
                        default=False, verbose_name="Puede editar palabras personalizadas"
                    ),
                ),
                (
                    "can_delete_wordlist",
                    models.BooleanField(
                        default=False,
                        verbose_name="Puede eliminar/reactivar palabras personalizadas",
                    ),
                ),
                (
                    "can_import_wordlist",
                    models.BooleanField(
                        default=False, verbose_name="Puede importar palabras personalizadas"
                    ),
                ),
                (
                    "can_export_wordlist",
                    models.BooleanField(
                        default=False, verbose_name="Puede exportar palabras personalizadas"
                    ),
                ),
                (
                    "can_history_wordlist",
                    models.BooleanField(
                        default=False, verbose_name="Puede ver histórico de cambios"
                    ),
                ),
                (
                    "scope_wordlist",
                    models.SmallIntegerField(
                        choices=apps.analytics.utils.get_scopes,
                        default=0,
                        verbose_name="Alcance del permiso",
                    ),
                ),
                (
                    "can_add_agent",
                    models.BooleanField(default=False, verbose_name="Puede añadir asesores"),
                ),
                (
                    "can_edit_agent",
                    models.BooleanField(default=False, verbose_name="Puede editar asesores"),
                ),
                (
                    "can_delete_agent",
                    models.BooleanField(
                        default=False, verbose_name="Puede eliminar/reactivar asesores"
                    ),
                ),
                (
                    "can_import_agent",
                    models.BooleanField(default=False, verbose_name="Puede importar asesores"),
                ),
                (
                    "can_export_agent",
                    models.BooleanField(default=False, verbose_name="Puede exportar asesores"),
                ),
                (
                    "can_history_agent",
                    models.BooleanField(
                        default=False, verbose_name="Puede ver histórico de cambios"
                    ),
                ),
                (
                    "scope_agent",
                    models.SmallIntegerField(
                        choices=apps.analytics.utils.get_scopes,
                        default=0,
                        verbose_name="Alcance del permiso",
                    ),
                ),
                (
                    "can_add_campaign",
                    models.BooleanField(default=False, verbose_name="Puede añadir campañas"),
                ),
                (
                    "can_edit_campaign",
                    models.BooleanField(default=False, verbose_name="Puede editar campañas"),
                ),
                (
                    "can_delete_campaign",
                    models.BooleanField(
                        default=False, verbose_name="Puede eliminar/reactivar campañas"
                    ),
                ),
                (
                    "can_export_campaign",
                    models.BooleanField(default=False, verbose_name="Puede exportar campañas"),
                ),
                (
                    "can_history_campaign",
                    models.BooleanField(
                        default=False, verbose_name="Puede ver histórico de cambios"
                    ),
                ),
                (
                    "can_edit_config",
                    models.BooleanField(default=False, verbose_name="Puede editar configuraciones"),
                ),
                (
                    "can_history_config",
                    models.BooleanField(
                        default=False, verbose_name="Puede ver histórico de cambios"
                    ),
                ),
                (
                    "can_add_user",
                    models.BooleanField(default=False, verbose_name="Puede añadir usuarios"),
                ),
                (
                    "can_edit_user",
                    models.BooleanField(default=False, verbose_name="Puede editar usuarios"),
                ),
                (
                    "can_delete_user",
                    models.BooleanField(
                        default=False, verbose_name="Puede eliminar/reactivar usuarios"
                    ),
                ),
                (
                    "can_import_user",
                    models.BooleanField(default=False, verbose_name="Puede importar usuarios"),
                ),
                (
                    "can_export_user",
                    models.BooleanField(default=False, verbose_name="Puede exportar usuarios"),
                ),
                (
                    "can_history_user",
                    models.BooleanField(
                        default=False, verbose_name="Puede ver histórico de cambios"
                    ),
                ),
                (
                    "can_change_user_password",
                    models.BooleanField(default=False, verbose_name="Puede cambiar la contraseña"),
                ),
                (
                    "scope_user",
                    models.SmallIntegerField(
                        choices=apps.analytics.utils.get_scopes,
                        default=0,
                        verbose_name="Alcance del permiso",
                    ),
                ),
                (
                    "can_add_role",
                    models.BooleanField(default=False, verbose_name="Puede añadir roles"),
                ),
                (
                    "can_edit_role",
                    models.BooleanField(default=False, verbose_name="Puede editar roles"),
                ),
                (
                    "can_delete_role",
                    models.BooleanField(
                        default=False, verbose_name="Puede eliminar/reactivar roles"
                    ),
                ),
                (
                    "can_export_role",
                    models.BooleanField(default=False, verbose_name="Puede exportar roles"),
                ),
                (
                    "can_history_role",
                    models.BooleanField(
                        default=False, verbose_name="Puede ver histórico de cambios"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=30,
                        validators=[maintenance.validators.only_digits],
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "document_type",
                    models.PositiveSmallIntegerField(choices=[(1, "DNI"), (3, "CE")]),
                ),
                (
                    "document_number",
                    models.CharField(
                        max_length=20, validators=[maintenance.validators.only_digits]
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Nombre")),
                (
                    "is_active",
                    models.BooleanField(default=True, editable=False, verbose_name="Activo"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
            ],
            options={
                "verbose_name": "Campaña",
                "constraints": [models.UniqueConstraint(fields=("name",), name="campaign_unique")],
            },
            bases=(models.Model, maintenance.models.MaintenanceMixin),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=30,
                        validators=[maintenance.validators.only_digits],
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "document_type",
                    models.PositiveSmallIntegerField(choices=[(1, "DNI"), (3, "CE")]),
                ),
                (
                    "document_number",
                    models.CharField(
                        max_length=20, validators=[maintenance.validators.only_digits]
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.campaign",
                        verbose_name="Campaña",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "ordering": ("-is_active", "first_name", "last_name"),
            },
            bases=(models.Model, maintenance.models.MaintenanceMixin),
            managers=[
                ("objects", apps.users.models.UserCustomManager()),
                ("todos", django.contrib.auth.models.UserManager()),
            ],
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="campaign",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "users_campaignevent" ("create_date", "description", "id", "is_active", "modify_date", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."create_date", NEW."description", NEW."id", NEW."is_active", NEW."modify_date", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;',
                    hash="dd2dea624e2dd5a4fc9d0adb0bb70453686da52f",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_f82ff",
                    table="users_campaign",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="campaign",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "users_campaignevent" ("create_date", "description", "id", "is_active", "modify_date", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."create_date", NEW."description", NEW."id", NEW."is_active", NEW."modify_date", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;',
                    hash="7c2d8183136705c8c191ce793720b378198839ab",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_8c6c6",
                    table="users_campaign",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="campaignevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="campaignevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="users.campaign",
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(fields=("name",), name="role_unique"),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.role", verbose_name="Rol"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="role",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "users_roleevent" ("can_add_agent", "can_add_campaign", "can_add_process", "can_add_role", "can_add_typification", "can_add_user", "can_add_wordlist", "can_change_user_password", "can_delete_agent", "can_delete_campaign", "can_delete_process", "can_delete_role", "can_delete_typification", "can_delete_user", "can_delete_wordlist", "can_edit_agent", "can_edit_campaign", "can_edit_config", "can_edit_process", "can_edit_role", "can_edit_typification", "can_edit_user", "can_edit_wordlist", "can_export_agent", "can_export_campaign", "can_export_processresult", "can_export_role", "can_export_typification", "can_export_user", "can_export_wordlist", "can_history_agent", "can_history_campaign", "can_history_config", "can_history_process", "can_history_processresult", "can_history_role", "can_history_typification", "can_history_user", "can_history_wordlist", "can_import_agent", "can_import_typification", "can_import_user", "can_import_wordlist", "create_date", "id", "is_active", "modify_date", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scope_agent", "scope_process", "scope_processresult", "scope_typification", "scope_user", "scope_wordlist") VALUES (NEW."can_add_agent", NEW."can_add_campaign", NEW."can_add_process", NEW."can_add_role", NEW."can_add_typification", NEW."can_add_user", NEW."can_add_wordlist", NEW."can_change_user_password", NEW."can_delete_agent", NEW."can_delete_campaign", NEW."can_delete_process", NEW."can_delete_role", NEW."can_delete_typification", NEW."can_delete_user", NEW."can_delete_wordlist", NEW."can_edit_agent", NEW."can_edit_campaign", NEW."can_edit_config", NEW."can_edit_process", NEW."can_edit_role", NEW."can_edit_typification", NEW."can_edit_user", NEW."can_edit_wordlist", NEW."can_export_agent", NEW."can_export_campaign", NEW."can_export_processresult", NEW."can_export_role", NEW."can_export_typification", NEW."can_export_user", NEW."can_export_wordlist", NEW."can_history_agent", NEW."can_history_campaign", NEW."can_history_config", NEW."can_history_process", NEW."can_history_processresult", NEW."can_history_role", NEW."can_history_typification", NEW."can_history_user", NEW."can_history_wordlist", NEW."can_import_agent", NEW."can_import_typification", NEW."can_import_user", NEW."can_import_wordlist", NEW."create_date", NEW."id", NEW."is_active", NEW."modify_date", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."scope_agent", NEW."scope_process", NEW."scope_processresult", NEW."scope_typification", NEW."scope_user", NEW."scope_wordlist"); RETURN NULL;',
                    hash="ebb6a90587e2990eaae6c98ea44ee5cb86e4ee99",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_204d5",
                    table="users_role",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="role",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "users_roleevent" ("can_add_agent", "can_add_campaign", "can_add_process", "can_add_role", "can_add_typification", "can_add_user", "can_add_wordlist", "can_change_user_password", "can_delete_agent", "can_delete_campaign", "can_delete_process", "can_delete_role", "can_delete_typification", "can_delete_user", "can_delete_wordlist", "can_edit_agent", "can_edit_campaign", "can_edit_config", "can_edit_process", "can_edit_role", "can_edit_typification", "can_edit_user", "can_edit_wordlist", "can_export_agent", "can_export_campaign", "can_export_processresult", "can_export_role", "can_export_typification", "can_export_user", "can_export_wordlist", "can_history_agent", "can_history_campaign", "can_history_config", "can_history_process", "can_history_processresult", "can_history_role", "can_history_typification", "can_history_user", "can_history_wordlist", "can_import_agent", "can_import_typification", "can_import_user", "can_import_wordlist", "create_date", "id", "is_active", "modify_date", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scope_agent", "scope_process", "scope_processresult", "scope_typification", "scope_user", "scope_wordlist") VALUES (NEW."can_add_agent", NEW."can_add_campaign", NEW."can_add_process", NEW."can_add_role", NEW."can_add_typification", NEW."can_add_user", NEW."can_add_wordlist", NEW."can_change_user_password", NEW."can_delete_agent", NEW."can_delete_campaign", NEW."can_delete_process", NEW."can_delete_role", NEW."can_delete_typification", NEW."can_delete_user", NEW."can_delete_wordlist", NEW."can_edit_agent", NEW."can_edit_campaign", NEW."can_edit_config", NEW."can_edit_process", NEW."can_edit_role", NEW."can_edit_typification", NEW."can_edit_user", NEW."can_edit_wordlist", NEW."can_export_agent", NEW."can_export_campaign", NEW."can_export_processresult", NEW."can_export_role", NEW."can_export_typification", NEW."can_export_user", NEW."can_export_wordlist", NEW."can_history_agent", NEW."can_history_campaign", NEW."can_history_config", NEW."can_history_process", NEW."can_history_processresult", NEW."can_history_role", NEW."can_history_typification", NEW."can_history_user", NEW."can_history_wordlist", NEW."can_import_agent", NEW."can_import_typification", NEW."can_import_user", NEW."can_import_wordlist", NEW."create_date", NEW."id", NEW."is_active", NEW."modify_date", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."scope_agent", NEW."scope_process", NEW."scope_processresult", NEW."scope_typification", NEW."scope_user", NEW."scope_wordlist"); RETURN NULL;',
                    hash="ff1236c546cde2d9797650a2bb7858536e6a9a12",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_5666e",
                    table="users_role",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="roleevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="roleevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="users.role",
            ),
        ),
        migrations.AddField(
            model_name="userevent",
            name="campaign",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="users.campaign",
                verbose_name="Campaña",
            ),
        ),
        migrations.AddField(
            model_name="userevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="userevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userevent",
            name="role",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="users.role",
                verbose_name="Rol",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(fields=("username",), name="user_unique"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role_id", 1)), fields=("role",), name="user_admin_role_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("campaign_id", 1)),
                fields=("campaign",),
                name="user_admin_campaign_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_superuser", True)),
                fields=("is_superuser",),
                name="user_superuser_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_staff", True)),
                fields=("is_staff",),
                name="user_staffuser_unique",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "users_userevent" ("campaign_id", "date_joined", "document_number", "document_type", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_id", "username") VALUES (NEW."campaign_id", NEW."date_joined", NEW."document_number", NEW."document_type", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_login", NEW."last_name", NEW."password", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."role_id", NEW."username"); RETURN NULL;',
                    hash="1ed3efe1e17abb41edae2b3acd10b8e34166bdba",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_52e78",
                    table="users_user",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "users_userevent" ("campaign_id", "date_joined", "document_number", "document_type", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_id", "username") VALUES (NEW."campaign_id", NEW."date_joined", NEW."document_number", NEW."document_type", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_login", NEW."last_name", NEW."password", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."role_id", NEW."username"); RETURN NULL;',
                    hash="3baf9ef00a092643d3c9ec82d610fa2019156d02",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_16e22",
                    table="users_user",
                    when="AFTER",
                ),
            ),
        ),
    ]
