DOCUMENT_DNI = 1
DOCUMENT_RUC = 2
DOCUMENT_CE = 3
DOCUMENT_PASAPORTE = 4

DOCUMENT_USER_CHOICES = ((DOCUMENT_DNI, "DNI"), (DOCUMENT_CE, "CE"))

SCOPE_NONE = 0
SCOPE_USER = 1
SCOPE_CAMPAIGN = 2
SCOPE_GLOBAL = 3

PROCESS_STATE_NO_AUDIOS = 1
PROCESS_STATE_READY = 2
PROCESS_STATE_TRANSCRIBED = 9
PROCESS_STATE_TRANSCRIBED_PARTIAL = 20
PROCESS_STATE_FINISHED = 13
PROCESS_STATE_FINISHED_PARTIAL = 21


PROCESS_STATE_CLEANING_UPLOADING_ERROR = 3
PROCESS_STATE_UPLOADING_ERROR = 4
PROCESS_STATE_UPLOADING_STOPPED = 5
PROCESS_STATE_UPLOADED = 6
PROCESS_STATE_TRANSCRIBING_ERROR = 7
PROCESS_STATE_TRANSCRIBING_STOPPED = 8

PROCESS_STATE_CLEANING_TYPIFYING_ERROR = 10
PROCESS_STATE_TYPIFYING_ERROR = 11
PROCESS_STATE_TYPIFYING_STOPPED = 12


MENU_PROCESS = "12"
MENU_RESULT = "13"

API_ACTION_MAIN = "main"
API_ACTION_START = "start"
API_ACTION_PAUSE = "pause"
API_ACTION_CONTINUE = "continue"
API_ACTION_RESTART = "restart"
API_ACTION_EXPORT_INDIVIDUAL = "export_individual"

JOB_AWS_TRANSCRIBE_PREFIX = "speech_analytics"

PROCESS_AUTO_REFRESH_SECONDS = 5

PROCESS_RESULT_MATCH = 1
PROCESS_RESULT_NO_MATCH = 2
PROCESS_RESULT_ERROR = 3

RESTART_EXTRA_FULL = 1
RESTART_EXTRA_PARTIAL = 2
RESTART_EXTRA_RESET_TYPIFY = 3
RESTART_EXTRA_RESET_NEW = 4

AUDIO_SLOWDOWN_FACTOR_MIN = 0.7
AUDIO_SLOWDOWN_FACTOR_MAX = 0.95

SLOP_MIN = 1
SLOP_MAX = 5

ADMIN_CAMPAIGN_ID = 1
ADMIN_USER_ID = 1
ADMIN_ROLE_ID = 1

CONSTRAINT_CAMPAIGN_UNIQUE_NAME = "campaign_unique"
CONSTRAINT_ROLE_UNIQUE_NAME = "role_unique"
CONSTRAINT_USER_UNIQUE_USERNAME = "user_unique"
CONSTRAINT_USER_UNIQUE_ROLE_ADMIN = "user_admin_role_unique"
CONSTRAINT_USER_UNIQUE_CAMPAIGN_ADMIN = "user_admin_campaign_unique"
CONSTRAINT_USER_UNIQUE_SUPER_USER = "user_superuser_unique"
CONSTRAINT_USER_UNIQUE_STAFF_USER = "user_staffuser_unique"
CONSTRAINT_WORD_UNIQUE_WORD_WORDLIST = "word_unique"
CONSTRAINT_AGENT_UNIQUE_NAME_CAMPAIGN = "agent_unique"
CONSTRAINT_WORDLIST_UNIQUE_NAME_CAMPAIGN = "wordlist_unique"
CONSTRAINT_TYPIFICATION_UNIQUE_NAME_CAMPAIGN = "typification_unique"
CONSTRAINT_PATTERN_UNIQUE_SENTENCE_TYPIFICATION = "pattern_unique"
CONSTRAINT_PROCESS_UNIQUE_NAME_CREATE_USER = "process_unique"
CONSTRAINT_PROCESSRESULT_UNIQUE_AUDIO_TYPIFICATION = "processresult_unique"

SEARCH_PROCESS_STATE_NO_AUDIOS = "no_audios"
SEARCH_PROCESS_STATE_READY = "ready"
SEARCH_PROCESS_STATE_TRANSCRIBED = "transcribed"
SEARCH_PROCESS_STATE_FINISHED = "finished"

SEARCH_PROCESS_RESULT_MATCH = "match"
SEARCH_PROCESS_RESULT_NO_MATCH = "no_match"
SEARCH_PROCESS_RESULT_ERROR = "error"

PROJECT_NAME = "Speech Analytics"

PROCESS_TYPE_AWS = 1
PROCESS_TYPE_LOCAL = 2

LOCALAI_MODE_QUALITY = 1
LOCALAI_MODE_PERFORMANCE = 2
