# Generated by Django 5.2.1 on 2025-10-14 17:06

from django.db import migrations, models

import maintenance.models

import apps.analytics.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, editable=False, verbose_name="Activo"),
                ),
                ("name", models.CharField(verbose_name="Nombre Completo")),
            ],
            options={"verbose_name": "Asesor", "verbose_name_plural": "Asesores"},
            bases=(models.Model, maintenance.models.MaintenanceMixin),
        ),
        migrations.CreateModel(
            name="AgentEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, editable=False, verbose_name="Activo"),
                ),
                ("name", models.CharField(verbose_name="Nombre Completo")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, editable=False, verbose_name="Activo"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.analytics.utils.get_new_name_audio_folder,
                        verbose_name="Archivo de audio",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        editable=False, max_length=255, verbose_name="Nombre original del archivo"
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(editable=False, verbose_name="Duración"),
                ),
                (
                    "transcription",
                    models.JSONField(editable=False, null=True, verbose_name="Transcripción"),
                ),
                ("agent_date", models.DateField(verbose_name="Fecha asesor")),
                (
                    "transcription_start_date",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="Fecha inicio transcripción"
                    ),
                ),
                (
                    "transcription_end_date",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="Fecha fin transcripción"
                    ),
                ),
                (
                    "typify_start_date",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="Fecha inicio tipificación"
                    ),
                ),
                (
                    "typify_end_date",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="Fecha fin tipificación"
                    ),
                ),
                (
                    "process_error_details",
                    models.TextField(editable=False, verbose_name="Error último proceso"),
                ),
            ],
            options={"verbose_name": "Audio"},
            bases=(models.Model, maintenance.models.MaintenanceMixin),
        ),
        migrations.CreateModel(
            name="AudioEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, editable=False, verbose_name="Activo"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.analytics.utils.get_new_name_audio_folder,
                        verbose_name="Archivo de audio",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        editable=False, max_length=255, verbose_name="Nombre original del archivo"
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(editable=False, verbose_name="Duración"),
                ),
                (
                    "transcription",
                    models.JSONField(editable=False, null=True, verbose_name="Transcripción"),
                ),
                ("agent_date", models.DateField(verbose_name="Fecha asesor")),
                (
                    "transcription_start_date",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="Fecha inicio transcripción"
                    ),
                ),
                (
                    "transcription_end_date",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="Fecha fin transcripción"
                    ),
                ),
                (
                    "typify_start_date",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="Fecha inicio tipificación"
                    ),
                ),
                (
                    "typify_end_date",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="Fecha fin tipificación"
                    ),
                ),
                (
                    "process_error_details",
                    models.TextField(editable=False, verbose_name="Error último proceso"),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="AudioSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Orden en conversación")),
                ("text", models.TextField(verbose_name="Texto")),
                ("start_time", models.FloatField(verbose_name="Hora de inicio")),
                ("end_time", models.FloatField(verbose_name="Hora de fin")),
                ("speaker_label", models.CharField(verbose_name="Interlocutor")),
            ],
            options={
                "verbose_name": "Segmento de audio",
                "verbose_name_plural": "Segmentos de audio",
            },
            bases=(models.Model, maintenance.models.MaintenanceMixin),
        ),
        migrations.CreateModel(
            name="Pattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, editable=False, verbose_name="Activo"),
                ),
                ("sentence", models.CharField(verbose_name="Oración")),
            ],
            options={"verbose_name": "Patrón", "verbose_name_plural": "Patrones"},
            bases=(models.Model, maintenance.models.MaintenanceMixin),
        ),
        migrations.CreateModel(
            name="PatternEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, editable=False, verbose_name="Activo"),
                ),
                ("sentence", models.CharField(verbose_name="Oración")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, editable=False, verbose_name="Activo"),
                ),
                ("name", models.CharField(verbose_name="Nombre")),
                (
                    "state",
                    models.IntegerField(
                        choices=apps.analytics.utils.get_process_states,
                        default=1,
                        editable=False,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=apps.analytics.utils.get_process_types,
                        default=1,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "tries",
                    models.PositiveSmallIntegerField(
                        default=0, editable=False, verbose_name="Intentos"
                    ),
                ),
                (
                    "start_process",
                    models.DateTimeField(editable=False, null=True, verbose_name="Hora de inicio"),
                ),
                (
                    "end_transcribe_upload_audios",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="Fin de subida de audios"
                    ),
                ),
                (
                    "end_transcribe_create_jobs",
                    models.DateTimeField(
                        editable=False,
                        null=True,
                        verbose_name="Fin de creación de Tareas de transcripción",
                    ),
                ),
                (
                    "end_transcribe_get_results",
                    models.DateTimeField(
                        editable=False,
                        null=True,
                        verbose_name="Fin de obtener resultados de transcripción",
                    ),
                ),
                (
                    "end_typify_start",
                    models.DateTimeField(
                        editable=False,
                        null=True,
                        verbose_name="Fin de creación de migración a Elasticsearch",
                    ),
                ),
                (
                    "end_typify_get_results",
                    models.DateTimeField(
                        editable=False,
                        null=True,
                        verbose_name="Fin de obtener resultados de queries",
                    ),
                ),
                (
                    "end_process",
                    models.DateTimeField(editable=False, null=True, verbose_name="Hora de fin"),
                ),
                (
                    "details",
                    models.TextField(blank=True, editable=False, verbose_name="Detalles error"),
                ),
                (
                    "had_errors",
                    models.BooleanField(default=False, editable=False, verbose_name="Hubo errores"),
                ),
                (
                    "was_stopped",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Se pausó manualmente"
                    ),
                ),
                (
                    "was_stopped_date",
                    models.DateTimeField(editable=False, null=True, verbose_name="Hora pausa"),
                ),
                (
                    "is_running",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Se está procesando actualmente"
                    ),
                ),
            ],
            options={
                "verbose_name": "Procesado de Audios",
                "verbose_name_plural": "Procesados de Audios",
            },
            bases=(models.Model, maintenance.models.MaintenanceMixin),
        ),
        migrations.CreateModel(
            name="ProcessEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, editable=False, verbose_name="Activo"),
                ),
                ("name", models.CharField(verbose_name="Nombre")),
                (
                    "state",
                    models.IntegerField(
                        choices=apps.analytics.utils.get_process_states,
                        default=1,
                        editable=False,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=apps.analytics.utils.get_process_types,
                        default=1,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "tries",
                    models.PositiveSmallIntegerField(
                        default=0, editable=False, verbose_name="Intentos"
                    ),
                ),
                (
                    "start_process",
                    models.DateTimeField(editable=False, null=True, verbose_name="Hora de inicio"),
                ),
                (
                    "end_transcribe_upload_audios",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="Fin de subida de audios"
                    ),
                ),
                (
                    "end_transcribe_create_jobs",
                    models.DateTimeField(
                        editable=False,
                        null=True,
                        verbose_name="Fin de creación de Tareas de transcripción",
                    ),
                ),
                (
                    "end_transcribe_get_results",
                    models.DateTimeField(
                        editable=False,
                        null=True,
                        verbose_name="Fin de obtener resultados de transcripción",
                    ),
                ),
                (
                    "end_typify_start",
                    models.DateTimeField(
                        editable=False,
                        null=True,
                        verbose_name="Fin de creación de migración a Elasticsearch",
                    ),
                ),
                (
                    "end_typify_get_results",
                    models.DateTimeField(
                        editable=False,
                        null=True,
                        verbose_name="Fin de obtener resultados de queries",
                    ),
                ),
                (
                    "end_process",
                    models.DateTimeField(editable=False, null=True, verbose_name="Hora de fin"),
                ),
                (
                    "details",
                    models.TextField(blank=True, editable=False, verbose_name="Detalles error"),
                ),
                (
                    "had_errors",
                    models.BooleanField(default=False, editable=False, verbose_name="Hubo errores"),
                ),
                (
                    "was_stopped",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Se pausó manualmente"
                    ),
                ),
                (
                    "was_stopped_date",
                    models.DateTimeField(editable=False, null=True, verbose_name="Hora pausa"),
                ),
                (
                    "is_running",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Se está procesando actualmente"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ProcessResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                ("agent_date", models.DateField(verbose_name="Fecha asesor")),
                (
                    "pattern_matched_sentence",
                    models.CharField(blank=True, verbose_name="Oración que hizo match"),
                ),
                (
                    "audio_segment_text",
                    models.CharField(blank=True, verbose_name="Transcripción coincidente"),
                ),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=apps.analytics.utils.get_process_result_states,
                        default=2,
                        verbose_name="Estado",
                    ),
                ),
                ("score", models.FloatField(null=True, verbose_name="Score interno")),
                ("obs", models.TextField(blank=True, verbose_name="Observaciones")),
            ],
            options={
                "verbose_name": "Análisis de audios",
                "verbose_name_plural": "Análisis de audios",
            },
            bases=(models.Model, maintenance.models.MaintenanceMixin),
        ),
        migrations.CreateModel(
            name="Typification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, editable=False, verbose_name="Activo"),
                ),
                ("name", models.CharField(verbose_name="Nombre")),
            ],
            options={"verbose_name": "Tipificación", "verbose_name_plural": "Tipificaciones"},
            bases=(models.Model, maintenance.models.MaintenanceMixin),
        ),
        migrations.CreateModel(
            name="TypificationEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, editable=False, verbose_name="Activo"),
                ),
                ("name", models.CharField(verbose_name="Nombre")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, editable=False, verbose_name="Activo"),
                ),
                ("word", models.CharField(verbose_name="Palabra")),
            ],
            options={"verbose_name": "Palabra"},
            bases=(models.Model, maintenance.models.MaintenanceMixin),
        ),
        migrations.CreateModel(
            name="WordEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, editable=False, verbose_name="Activo"),
                ),
                ("word", models.CharField(verbose_name="Palabra")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="WordList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, editable=False, verbose_name="Activo"),
                ),
                ("name", models.CharField(verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Palabras Personalizadas",
                "verbose_name_plural": "Palabras Personalizadas",
            },
            bases=(models.Model, maintenance.models.MaintenanceMixin),
        ),
        migrations.CreateModel(
            name="WordListEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, editable=False, verbose_name="Activo"),
                ),
                ("name", models.CharField(verbose_name="Nombre")),
            ],
            options={"abstract": False},
        ),
    ]
