# Generated by Django 5.2.7 on 2025-11-12 08:28

from django.db import migrations, models

import apps.analytics.utils


class Migration(migrations.Migration):

    dependencies = [("analytics", "0002_initial")]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=apps.analytics.utils.get_process_types, default=2, verbose_name="Tipo"
            ),
        ),
        migrations.AlterField(
            model_name="processevent",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=apps.analytics.utils.get_process_types, default=2, verbose_name="Tipo"
            ),
        ),
    ]
